# Generated by Django 3.0.6 on 2020-05-18 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=50)),
                ('dataset_type', models.CharField(choices=[('text_documents', 'text_documents'), ('json', 'json'), ('csv', 'csv'), ('images', 'images')], default='text_documents', max_length=255)),
                ('dataset_location', models.CharField(choices=[('file_system', 'file_system'), ('database', 'database'), ('remote', 'remote')], default='file_system', max_length=255)),
                ('dataset_path', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ModelVectorSpace',
            fields=[
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('status', models.BooleanField(default=False)),
                ('id', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('tf_func', models.CharField(choices=[('normal', 'normal'), ('logarithm', 'logarithm'), ('augmented', 'augmented'), ('boolean', 'boolean'), ('log_ave', 'log_ave')], default='normal', max_length=50)),
                ('idf_func', models.CharField(choices=[('no', 'no'), ('idf', 'idf'), ('prob_idf', 'prob_idf')], default='idf', max_length=50)),
                ('norm_func', models.CharField(choices=[('none', 'none'), ('cosine', 'cosine')], max_length=50)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Dataset', verbose_name='Classification Dataset')),
            ],
            options={
                'get_latest_by': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='KNNClasification',
            fields=[
                ('model', picklefield.fields.PickledObjectField(editable=False)),
                ('id', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('train_size', models.FloatField(default=0.8)),
                ('test_size', models.FloatField(default=0.2)),
                ('cv_size', models.FloatField(default=0)),
                ('k', models.IntegerField(default=3, help_text='K for K Neighbors')),
                ('distance_formula', models.CharField(choices=[('cosine_similarity', 'cosine_similarity'), ('euclidian_distance', 'euclidian_distance')], max_length=255)),
                ('accuracy', models.FloatField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Dataset', verbose_name='Classification Dataset')),
                ('vector_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.ModelVectorSpace', verbose_name='Classification Vector Space')),
            ],
        ),
    ]
