# Generated by Django 3.0.7 on 2020-06-08 18:33

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvectorspace',
            name='data',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='modelvectorspace',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
