# Generated by Django 3.0.7 on 2020-06-08 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20200608_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.DateTimeField(default=datetime.date.today, primary_key=True, serialize=False),
        ),
    ]
