# Generated by Django 3.0.7 on 2020-06-08 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_auto_20200518_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelvectorspace',
            options={'get_latest_by': ['id']},
        ),
        migrations.CreateModel(
            name='ClassificationMlModel',
            fields=[
                ('model', picklefield.fields.PickledObjectField(editable=False)),
                ('id', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('train_size', models.FloatField(default=0.8)),
                ('test_size', models.FloatField(default=0.2)),
                ('cv_size', models.FloatField(default=0)),
                ('ml_model_type', models.CharField(choices=[('RandomForestClassifier', 'RandomForestClassifier'), ('LogisticRegression', 'LogisticRegression')], max_length=256)),
                ('distance_formula', models.CharField(choices=[('cosine_similarity', 'cosine_similarity'), ('euclidian_distance', 'euclidian_distance')], max_length=255)),
                ('accuracy', models.FloatField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Dataset', verbose_name='Classification Dataset')),
                ('vector_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.ModelVectorSpace', verbose_name='Classification Vector Space')),
            ],
            options={
                'get_latest_by': ['time_created'],
            },
        ),
    ]
