# Generated by Django 3.0.7 on 2020-06-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_auto_20200608_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationmlmodel',
            name='model',
        ),
        migrations.AddField(
            model_name='classificationmlmodel',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
