# Generated by Django 3.0.6 on 2020-05-18 00:58

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VectorSpaceModel',
            fields=[
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('status', models.BooleanField(default=False)),
                ('id', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('tf_func', models.CharField(choices=[('normal', 'normal'), ('logarithm', 'logarithm'), ('augmented', 'augmented'), ('boolean', 'boolean'), ('log_ave', 'log_ave')], max_length=50)),
                ('idf_func', models.CharField(choices=[('no', 'no'), ('idf', 'idf'), ('prob_idf', 'prob_idf')], max_length=50)),
                ('norm_func', models.CharField(choices=[('none', 'none'), ('cosine', 'cosine')], max_length=50)),
            ],
        ),
    ]
