# Generated by Django 3.0.6 on 2020-05-18 00:58

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMeansClustering',
            fields=[
                ('model', picklefield.fields.PickledObjectField(editable=False)),
                ('id', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('train_size', models.FloatField(default=0.8)),
                ('test_size', models.FloatField(default=0.2)),
                ('cv_size', models.FloatField(default=0)),
                ('n_clusters', models.IntegerField(default=3, help_text='Number of Clusteres')),
                ('distance_formula', models.CharField(choices=[('cosine_similarity', 'cosine_similarity'), ('euclidian_distance', 'euclidian_distance')], max_length=255)),
                ('labels', picklefield.fields.PickledObjectField(editable=False)),
                ('file_names', picklefield.fields.PickledObjectField(editable=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Dataset', verbose_name='Clustering Dataset')),
                ('vector_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.ModelVectorSpace', verbose_name='Clustering Vector Space')),
            ],
        ),
    ]
